# Generated by Django 4.1.6 on 2023-02-05 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empname", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("contact", models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deptname", models.CharField(max_length=50)),
                (
                    "manager",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="Home.employee"
                    ),
                ),
            ],
        ),
    ]
