# Generated by Django 4.1.6 on 2023-02-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0002_alter_department_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="manager",
            field=models.CharField(default="no", max_length=10),
            preserve_default=False,
        ),
    ]
