# Generated by Django 4.1.6 on 2023-02-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0003_employee_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="manager",
            field=models.CharField(default="no", max_length=10),
        ),
    ]
